"""Add failure_config column to proxies

Revision ID: 12b40845a386
Revises: db6ce6daf884
Create Date: 2025-06-05 17:39:42.544435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b40845a386'
down_revision: Union[str, None] = 'db6ce6daf884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists before adding it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('proxies')]
    
    if 'failure_config' not in columns:
        op.add_column('proxies', sa.Column('failure_config', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies', 'failure_config')
    # ### end Alembic commands ###
