"""remove_model_name_from_proxy

Revision ID: 727f87f2b674
Revises: 12b40845a386
Create Date: 2025-06-05 19:59:35.918142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727f87f2b674'
down_revision: Union[str, None] = '12b40845a386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies', sa.Column('model_name', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
